"use client";
import { Link as ScrollLink  } from "react-scroll";
import Reactt, { useState, useEffect, } from 'react';
import { MdOutlinePlayArrow} from "react-icons/md";
import LogilabELNwhite from '../../public/assets/images/Logilab-ELN_white.svg'
import WOW from 'wowjs';
import "../globals.css"
import home_calender from '../../public/assets/images/home_calender.svg'
import Footer from '../footer';
import useScroll from '../useScroll';
// import 'slick-carousel/slick/slick.css';
// import 'slick-carousel/slick/slick-theme.css';
// import Slider from 'react-slick';
import  Link  from 'next/link'
// import Image from 'next/image';
// import Logo from '../assets/images/loglab_Eln.svg';
import Image from "next/image";
import search from '../../public/assets/images/search.svg'
import contact from '../../public/assets/images/contact.svg'
import setting from '../../public/assets/images/setting.svg'
import Acadamy from '../../public/assets/images/academics_icon.svg'
import Flow_structure from '../../public/assets/images/Flow_structure.svg'
import solution_customeraudit from '../../public/assets/images/solution_customeraudit.svg'
import Comprehensive_audit_trails from '../../public/assets/images/Comprehensive_audit_trails.svg'
// import loglab_Eln from '../../public/assets/images/loglab_Eln.svg';
// import loginewimage from '../../public/assets/images/loginewimage.svg'
import cta2 from '../../public/assets/images/cta2.svg'  
import type { Metadata } from "next";
import { useRouter } from 'next/router';
import Header from "@/components/header";
import { SyncLoader } from 'react-spinners';


const ProductPage = () => {
  const router = useRouter();
  const { productId } = router.query;

  return (
    <div>
      <h1>Product ID: {productId}</h1>
    </div>
  );
}



export default function Solution() {
  const [loading, setLoading] = useState(true);
  const [fadeOut, setFadeOut] = useState(false);
  const metadata: Metadata = {
    title: "solution",
    description: "Generated by create next app",
  };
 
  const { isSticky, nextSectionTop, lastContainerBottom, isHidden ,offset1, offset2, offset3,offset4,offset5 } = useScroll();
  useEffect(() => {
    const timer = setTimeout(() => {
      setFadeOut(true); // Trigger fade-out animation
      setTimeout(() => setLoading(false), 500); // Wait for animation to finish before hiding
    }, 1000); // Adjust duration
    return () => clearTimeout(timer);
  }, []);

  if (loading) {
    return (
      <div className={`preloader ${fadeOut ? 'fade-out' : ''}`}>
        <SyncLoader color="#1163ea" size={20} />
      </div>
    );
  }

return (
  <div>
        <Header/>
        <div className="soltionbg solutionmain security_banner_content">
          <div className="container">
          
              <div className="row">
                <div className="col-lg-12  d-flex d-flex justify-content-center pt-4 ">
                  <div className="solution_security_banner_content bannerresolution">
                    <h1 className="wow fadeInUp pt-3" data-wow-delay="0.3s">
                    Reliable, Versatile, Configurable
                    </h1>
                    <p className="f_400 w_color l_height28 wow fadeInUp text-center para_response" data-wow-delay="0.4s">
                      The ELN that works for all laboratories and industry verticals
                    </p>
                    <div className="d-flex action_btn justify-content-center mt_40 bannerresolution_btn" data-wow-delay="0.6s">
                      <Link href="/request-a-demo" className="btn btn--white text-center">
                       Request a Demo
                      </Link>
                      <Link href="/product-brochure-download" className="btn btn--white mx-4 text-center">
                        Download Brochure
                      </Link>
                    </div>
                    
                  </div>
                </div>
        
              </div>
      
            </div>
        </div>

 

                <div className="erp_banner_area_two">
                    <div className="section_intro bg-lblue">
                    </div>
                </div>
  
   
          <div className='container tab2 py-3 cardsection'>
                  {/* <div className="header_before"> */}
                  <div className="hosting_title sec_title erp_title text-center mb-4">

                      <h2 className="fw-bold text-center mb-4 mt-5" >One Notebook, Many Chapters</h2>
                    </div>
                  {/* </div> */}
              <div className='d-flex  justify-content-center'>
                    
                    <div className="One_notebook">
                      <div className="row app_service_info" >
                      {/* <div className=" app_service_info slider-container" >   */}
                      {/* <Slider {...sliderSettings}>  */}
                        
                          <div className="col-lg-3 ">
                              <Link href='/solution/integrity'>   
                              <div className="solution_app_service_item colorchange my-2" data-wow-delay="0.2s">           
                                    <Image src={search} className="img-fluid  elnimage_size pt-4 pb-4" alt="Enhance data discovery with Electronic Lab Notebook"/>
                                    <h5 className="fw-bold pt-3 pb-3 mobile_fontsize fw-bold text-dark">GxP Environments</h5>
                                    <p className="px-2 mobile_parasize">Adhere to all GxP regulatory standards without a hitch through 21  CFR Part 11 and EudraLex Annex 11 compliance.</p>
                                    <p className="text-center learmoresize"><ins>Learn More</ins></p>
                              </div>
                              </Link> 
                          </div>
                          <div className="col-lg-3">
                          <Link href='/solution/research'> 
                              <div className="solution_app_service_item colorchange my-2" data-wow-delay="0.2s">
                                  <Image src={contact} className="img-fluid  elnimage_size pt-4 pb-4" alt="Streamline your lab data management with Logilab Electronic Lab Notebook"/>
                                  <h5 className="fw-bold pt-4 pb-3 cardresolution mobile_fontsize fw-bold text-dark">Non-GxP Environments </h5>
                                  <p className="px-2 mobile_parasize">Reduce idea-to-execution lifecycles. Create SoPs, design templates, and run experiments and projects without any gaps.</p>
                                  <p className="text-center learmoresize"><ins>Learn More</ins></p>
                              </div>
                          </Link>    
                          </div>
                          <div className="col-lg-3">
                             
                            <Link href='/solution/qa_qc_lab'> 
                                <div className="solution_app_service_item colorchange my-2" data-wow-delay="0.2s">
                                    <Image src={setting} className="img-fluid  elnimage_size pt-4 pb-4" alt="Optimize lab productivity with Electronic Lab Notebook"/>
                                    <h5 className="fw-bold pt-3 pb-3 mobile_fontsize fw-bold text-dark">CROs</h5>
                                    <p className="px-2 mobile_parasize">Increase your value to your customers by employing SoPs, performing analysis and generating COAs on time.</p>
                                    <p className="text-center learmoresize"><ins>Learn More</ins> </p>
                                </div>
                            </Link>    
                          </div>
                          <div className="col-lg-3">
                            <Link href='/solution/academics'> 
                                <div className="solution_app_service_item colorchange my-2" data-wow-delay="0.2s">
                                    <Image src={Acadamy} className="img-fluid  elnimage_size pt-4 pb-4" alt="Budget-friendly Electronic Lab Notebook for students"/>
                                    <h5 className="fw-bold pt-3 pb-3 mobile_fontsize fw-bold text-dark">Academics</h5>
                                    <p className="px-2 mobile_parasize">Get ahead of your peers — ditch paper records, accelerate collaboration, and keep your lab’s budget at bay.</p>
                                    <p className="text-center learmoresize"><ins>Learn More</ins> </p>
                                </div>
                            </Link>   
                          </div> 
                      {/* </Slider> */}
                      </div>
                      
                    </div>


              </div>
          
          
          </div>
      
  

          <div id="sticky-anchor"></div>
          <div id="sticky" className={isSticky && !isHidden ? "stick" : ""}>
          <div className="tab-ara">
          <nav
            id="navbar-example2"
            className="navbar navbar-light px-3 pt-0 bg-body d-flex justify-content-center "
          >
            <ul className="nav nav-pills py-2">
              <li className="nav-item border-right">
                <ScrollLink
                  to="scrollspyHeading1"
                  data-nav="capture-contacts"
                  className="bottom_bodder text-center nav-link mx-3 "
                  aria-current="page"
                  spy={true}
                  smooth={true}
                  offset={offset1}
                  duration={20}
                >
                  <small className="mb-0 hover_bottom   f_900 border1">
                  QA & QC Labs{" "}
                  </small>
                </ScrollLink>
              </li>

              <li className="nav-item border-right">
                <ScrollLink
                  to="scrollspyHeading2"
                  data-nav="capture-contacts1"
                  className="bottom_bodder text-center nav-link mx-3 f_600"
                  aria-current="page"
                  spy={true}
                  smooth={true}
                  offset={offset2}
                  duration={20}
                >
                  <small className="mb-0 hover_bottom   f_900 border1">
                  R&D
                  </small>
                </ScrollLink>
              </li>
              <li className="nav-item border-right">
                <ScrollLink
                  to="scrollspyHeading3"
                  data-nav="capture-contacts2"
                  className="bottom_bodder text-center nav-link mx-3 f_600"
                  aria-current="page"
                  spy={true}
                  smooth={true}
                  offset={offset3}
                  duration={20}
                >
                  <small className="mb-0 hover_bottom   f_900 border1">
                  Data Integrity
                  </small>
                </ScrollLink>
              </li>
            </ul>
          </nav>
        </div>
        </div>



    {/* First*/}
    <div id="next-section">
    <div className="container py-5 mt-5 sectionresolution" id="scrollspyHeading1">
         <div className="row">
           <div className="col-lg-6 ">
           <div className="firstcontent_before">

                 <h3 className="solution_fontcolor fw-bold mb-2 topichead_response" >Logilab ELN for QA & QC labs</h3>
             <h6 className="fw-bold pb-3 topicsechead_response">Deliver consistent, accurate & reliable results effortlessly</h6>
              <div>
                <div className="d-flex w-50">
                  <p className="firstcontent1 text-center ps-3 mb-0 fw-bold text-black">Increase lab productivity</p>
                </div>
                <p className=" text-black pt-1 firstp">Paperless methods that standardize and streamline data</p>
              </div>

              <div>
                <div className="d-flex  w-50">
                  <p className="firstcontent2 text-center ps-3 mb-0 fw-bold text-black">Meet industry standards</p>
                </div>
                <p className="text-black pt-1 firstp">Maintain GLP and ensure reproducibility of data</p>
              </div>

              <div>
                <div className="d-flex  w-50">
                  <p className="firstcontent2 text-center fw-bold ps-3 mb-0 text-black">Data integrity</p>
                </div>
                <p className="text-black pt-1 firstp">Adhere to ALCOA principles and ensure secure data storage</p>
              </div>

              <div>
                <div className="d-flex  w-50">
                  <p className="firstcontent4 text-center ps-3 mb-0 fw-bold text-black">Compliance</p>
                </div>
                <p className="text-black pt-1 firstp">Full compliance to 21 CFR Part 11 and EudraLex Annex 11</p>
              </div>
            </div> 
           
              
           </div>
                <div className="col-lg-6   ">
                  <div className="researchfirst_border firstcontent_after p-4 image_postion sectionresolution"> 
                  <Image src={Comprehensive_audit_trails} className="img-fluid" 
                  alt="Standardize your research data, keep track of your inventory levels and stay compliant 
                  to regualtory standards such as Good Laboratory Practice with Logilab Electronic Lab Notebook."/>
                  </div>
                  
                </div>
         </div>
       </div>
     
    {/*second*/}

       <div className="container sectionresolution" id="scrollspyHeading2">
         <div className="row">

           <div className="col-lg-6 order-two">
            <div className="solutionSecond_border image_postion p-4 sectionresolution">
            <Image src={Flow_structure} className="img-fluid" 
            alt="Create dynamic SoPs, monitor task orders and configure streamlined workflows for your 
            R&D processes with Logilab Electronic Laboratory Notebook."/>  
            </div>
            
           </div>

           <div className="col-lg-6 ps-5 pt-2 sec_content_position sectionresolution">
             <div className="secondcontent_after ">
             <h3 className="solution_fontcolor fw-bold mb-2 topichead_response" >Logilab ELN for R&D</h3>
             <h6 className="fw-bold pb-3 topicsechead_response">Bring structure to your lab processes</h6>
              <div>
                <div className="d-flex w-50">
                  <p className="secondcontent1 text-center ps-3 mb-0 fw-bold text-black">All-in-one space</p>
                </div>
                <p className="text-black pt-1 secondp">Create a centralized,easily searchable cloud-based repository.</p>
              </div>

              <div>
                <div className="d-flex w-50">
                  <p className="secondcontent2 text-center ps-3 mb-0 fw-bold text-black">Capture complex data</p>
                </div>
                <p className="text-black pt-1 secondp">Dynamic data capture through user-designed protocols</p>
              </div>

              <div>
                <div className="d-flex w-50">
                  <p className="secondcontent2 text-center ps-3 mb-0 fw-bold text-black">Manage teams and projects</p>
                </div>
                   <p className="text-black pt-1 secondp contentpositonfit">Enhance communication and collaboration on projects — assign roles and privileges</p>  
              </div> 

              <div>
                <div className="d-flex w-50">
                  <p className="secondcontent4 text-center ps-3 mb-0 fw-bold text-black">Connect and condense</p>
                </div>
                <p className="text-black pt-1 secondp">Link data, sheets and protocols across multiple files</p>
              </div>
              
            </div> 
            
           </div>
          
         </div>
       </div>
  {/* Third Row */}
      
    <div className="container py-4 sectionresolution" id="scrollspyHeading3">
         <div className="row">
           <div className="col-lg-6 pt-5 sectionresolution">
              <div className="thirdcontent_before">
                <h3 className="solution_fontcolor fw-bold mb-2  topichead_response">Logilab ELN for 21 CFR Part 11 Compliance and Data Integrity 
                </h3>
                <h6 className="fw-bold pb-3 topicsechead_response">Ensure your lab data is safe & secure</h6>
                  <div>
                    <div className="d-flex w-50">
                        <p className="thirdcontent1 text-center ps-3 mb-0 fw-bold text-black">Electronic signatures</p>
                    </div>
                    <p className="text-black pt-1 thirdp">Validate modifications with support of e-signatures</p>
                  </div>

                  <div>
                    <div className="d-flex w-50">
                      <p className="thirdcontent2 text-center ps-3 mb-0 fw-bold text-black">Audit trails</p>
                    </div>
                    <p className="text-black pt-1 thirdp">See when, where and by whom changes were made</p>
                  </div>

                  <div>
                    <div className="d-flex w-50">
                      <p className="thirdcontent2 text-center ps-3 mb-0 fw-bold text-black">Version control</p>
                    </div>
                    <p className="text-black pt-1 thirdp">Ensure complete traceability and attributability of data</p>
                  </div>

                  <div>
                    <div className="d-flex w-50">
                      <p className="thirdcontent4   text-center ps-3 mb-0  fw-bold text-black">Reduce cost of compliance</p>
                    </div>
                    <p className="text-black pt-1 thirdp datintegrity">Achieve compliance with international regulatory standards without any compromise</p>
                  </div>
              </div>
        
              
           </div>

           <div className="col-lg-6  "> 
              <div className="soluttionthird_border p-4 thirdcontent_after image_postion sectionresolution">
              <Image src={solution_customeraudit} className="img-fluid" 
              alt="Logilab Electronic Laboratory Notebook's comprehensive audit trails, version control 
              and e-signs ensures full compliance to 21 CFR Part 11 and Good Laboratory Practice."/>    
              </div>
               
           </div>
         </div>
      </div>

      <div id="last-container">   
       <div className="cont backgr_col calender_cont">
                <div className="Devepoe_space">
                  <div className="">
                    <div className='container tab2 mt-3 py-5'>
                      <div className="row">
                        <div className="col-lg-6 d-flex flex-column justify-content-center align-items-center request-demo">
                          <div className=" text-center logpositionchange">
                              <h3 className="Ensure mt-3 f_800 l_height15 ensure-footer">Drive scientific progress forward with Logilab ELN
                              </h3>
                              <div className="d-flex justify-content-center align-items-center mt-4">
                                      <div className="action_btn job-button text-md cont_compare ">
                                          <Link href="https://logilabelnlite.azurewebsites.net/register" className="btn btn--blue  ">Get Started</Link>
                                      </div>
                                      <div className="action_btn job-button text-md Registorheader">
                                          <Link href="/pricing" className="btn btn--blue ms-4">Compare Plans</Link>
                                      </div>
                              </div>
                          </div>
                        </div>
                          <div className="col-lg-6 imageposition">    
                            <Image src={cta2} className="img-fluid w-75  imageposition-width" 
                            alt="Adopt Agaram's Logilab Electronic Lab Notebook to centralize your research 
                            data and stay compliant to 21 CFR Part 11, ALCOA principles, etc."/>                
                          </div>
                      </div>                     
                    </div>
                  </div>
                </div>
                    <div className=" last_imag_backgr pt-5">
                        <div className="container">
                    <div className="row">
                            <div className="col-lg-6 order-last order-lg-first">
                                <Image src={home_calender} className="img-fluid" 
                                alt="Contact Agaram Technologies to schedule a demo and discover how Logilab 
                                Electronic Laboratory Notebook can transform your lab's record-keeping."/>
                            </div>
                            <div className="col-lg-6 order-first order-lg-last d-flex flex-column justify-content-center align-items-center request-demo">                            
                                      <div className="text-center">
                                         <Image src={LogilabELNwhite} className="img-fluid responsive_image_bottom" alt=""/>
                                         <h3 className="text-white mt-3 f_800">Digitize. Simplify. Organize.</h3>
                                         <p className="Ensure-sub">Kickstart your paperless lab with Logilab ELN </p>
                                         <div className="action_btn d-flex justify-content-center align-items-center mt-4 request-demo"> 
                                          <Link href="/request-a-demo" className="btn btn--blue">Request a Demo</Link>         
                                  </div>
                                       </div>                                
                              
                            </div>
                        </div>                        
                    </div>
                    </div>
        </div>   


        
      </div>  

    </div>
     
         
        <Footer/> 
  </div>
  
);
}
